DROP TABLE Tags;
DROP TABLE Photos CASCADE CONSTRAINTS;
DROP TABLE Albums;
DROP TABLE Participants;
DROP TABLE User_Events;
DROP TABLE Education;
DROP TABLE Programs;
DROP TABLE Messages;
DROP TABLE User_Hometown_Cities;
DROP TABLE User_Current_Cities;
DROP TABLE Cities;
DROP TABLE Friends;
DROP TABLE Users;
DROP SEQUENCE city_sequence;
DROP SEQUENCE program_sequence;